"""CASS ML training pipeline.

Reads training data from ``training_data/{model_code}.json``, engineers
features over 60-minute windows, then trains and saves a model bundle to
``models/{model_code}.pkl``.

Usage:
    python -m training.train --model-code SRV-R740-2U
    python -m training.train --model-code SRV-R740-2U --all

The training_data JSON is generated by the simulator in offline mode.
If the file does not exist, the script prints instructions and exits.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import (
    GradientBoostingRegressor,
    IsolationForest,
    RandomForestClassifier,
)
from sklearn.model_selection import GroupShuffleSplit

# Add project root to path so training/ can import from app/
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from app.features import extract_features  # noqa: E402

TRAINING_DATA_DIR = PROJECT_ROOT / "training_data"
MODELS_DIR = PROJECT_ROOT / "models"

logging.basicConfig(
    stream=sys.stdout,
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data loading and windowing
# ---------------------------------------------------------------------------

def load_training_data(model_code: str) -> list[dict[str, Any]]:
    """Load flat telemetry + ground-truth records for one model_code."""
    path = TRAINING_DATA_DIR / f"{model_code}.json"
    if not path.exists():
        logger.error(
            "Training data not found: %s\n\n"
            "To generate it, run the simulator in offline mode:\n"
            "    cd simulator\n"
            "    node src/offline.js --model-code %s --output ../ml_service/training_data/%s.json\n"
            "\nThe simulator must be running and the CASS backend seeded with equipment models.",
            path, model_code, model_code,
        )
        sys.exit(1)

    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    logger.info("Loaded %d telemetry rows for model_code=%s", len(data), model_code)
    return data


def build_windowed_features(
    records: list[dict[str, Any]],
    passport: dict[str, Any],
    window_minutes: int = 60,
) -> pd.DataFrame:
    """Group records into 60-minute windows per unit and extract features.

    Expected record fields:
        unit_id, model_code, ts (ISO-8601), channel_code, value,
        true_health, active_mode (str | null), rul_true_hours

    Returns a DataFrame where each row is one window with feature columns
    plus target columns ``label`` (str mode code or "HEALTHY") and
    ``rul_hours`` (float).
    """
    df = pd.DataFrame(records)

    required = {"unit_id", "ts", "channel_code", "value"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Training data missing required columns: {missing}")

    df["ts"] = pd.to_datetime(df["ts"], utc=True)
    df["window_idx"] = df["ts"].dt.floor(f"{window_minutes}min")

    # Target: use the most recent value in the window for active_mode and rul
    if "active_mode" not in df.columns:
        df["active_mode"] = None
    if "rul_true_hours" not in df.columns:
        df["rul_true_hours"] = np.nan

    rows: list[dict[str, Any]] = []

    groups = df.groupby(["unit_id", "window_idx"])
    total = len(groups)
    logger.info("Windowing %d groups (unit × 60-min window) …", total)

    for (unit_id, window_ts), group in groups:
        window_records = group[["channel_code", "value"]].to_dict("records")
        if len(window_records) < 5:
            continue  # skip nearly empty windows

        features = extract_features(window_records, passport)
        if not features:
            continue

        # Take the most recent row's labels
        last_row = group.sort_values("ts").iloc[-1]
        active_mode = last_row.get("active_mode")
        rul = last_row.get("rul_true_hours", np.nan)

        label = str(active_mode) if active_mode and pd.notna(active_mode) else "HEALTHY"
        features["_unit_id"] = int(unit_id)
        features["_label"] = label
        features["_rul_hours"] = float(rul) if pd.notna(rul) else np.nan

        rows.append(features)

    if not rows:
        raise ValueError("No valid windows extracted — check training data format")

    result = pd.DataFrame(rows).fillna(0.0)
    logger.info(
        "Extracted %d windows, %d feature columns, labels: %s",
        len(result),
        len([c for c in result.columns if not c.startswith("_")]),
        result["_label"].value_counts().to_dict(),
    )
    return result


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_model_bundle(
    model_code: str,
    windowed_df: pd.DataFrame,
) -> dict[str, Any]:
    """Train all sub-models and return the bundle dict."""
    feature_cols = sorted([c for c in windowed_df.columns if not c.startswith("_")])

    X = windowed_df[feature_cols].values.astype(np.float64)
    y_label = windowed_df["_label"].values
    y_rul = windowed_df["_rul_hours"].values
    groups = windowed_df["_unit_id"].values

    # --- Train / validation split (80/20 by unit_id to avoid leakage) ---
    splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
    train_idx, val_idx = next(splitter.split(X, y_label, groups=groups))

    X_train, X_val = X[train_idx], X[val_idx]
    y_label_train, y_label_val = y_label[train_idx], y_label[val_idx]
    y_rul_train, y_rul_val = y_rul[train_idx], y_rul[val_idx]

    logger.info("Train set: %d windows | Val set: %d windows", len(X_train), len(X_val))

    # --- 1. IsolationForest — fit ONLY on HEALTHY samples ---
    healthy_mask = y_label_train == "HEALTHY"
    X_healthy = X_train[healthy_mask]
    if len(X_healthy) < 10:
        logger.warning(
            "Only %d HEALTHY windows for IsolationForest — "
            "consider generating more healthy baseline data",
            len(X_healthy),
        )
        X_iso_fit = X_train  # fallback: fit on all data
    else:
        X_iso_fit = X_healthy

    logger.info("Training IsolationForest on %d HEALTHY windows …", len(X_iso_fit))
    iso = IsolationForest(
        n_estimators=200,
        contamination=0.05,
        max_samples="auto",
        random_state=42,
        n_jobs=-1,
    )
    iso.fit(X_iso_fit)

    # --- 2. RandomForestClassifier (failure mode classification) ---
    unique_labels = sorted(set(y_label_train))
    logger.info("Training RandomForestClassifier on %d classes: %s …", len(unique_labels), unique_labels)
    clf = RandomForestClassifier(
        n_estimators=300,
        max_depth=12,
        min_samples_leaf=3,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )
    clf.fit(X_train, y_label_train)
    clf_acc = float(np.mean(clf.predict(X_val) == y_label_val))
    logger.info("Classifier val accuracy: %.3f", clf_acc)

    # --- 3. GradientBoostingRegressor × 3 (quantile RUL regression) ---
    # Only train where RUL is available (non-NaN)
    rul_mask_train = np.isfinite(y_rul_train)
    rul_mask_val = np.isfinite(y_rul_val)

    X_rul_train = X_train[rul_mask_train]
    y_rul_train_clean = y_rul_train[rul_mask_train]
    X_rul_val = X_val[rul_mask_val]
    y_rul_val_clean = y_rul_val[rul_mask_val]

    logger.info("Training GBR quantile regressors on %d windows with RUL labels …", len(X_rul_train))

    rul_q10 = rul_q50 = rul_q90 = None
    if len(X_rul_train) >= 20:
        common_gbr_params = dict(
            n_estimators=300,
            max_depth=4,
            learning_rate=0.05,
            min_samples_leaf=5,
            random_state=42,
        )
        rul_q10 = GradientBoostingRegressor(loss="quantile", alpha=0.1, **common_gbr_params)
        rul_q10.fit(X_rul_train, y_rul_train_clean)

        rul_q50 = GradientBoostingRegressor(loss="quantile", alpha=0.5, **common_gbr_params)
        rul_q50.fit(X_rul_train, y_rul_train_clean)

        rul_q90 = GradientBoostingRegressor(loss="quantile", alpha=0.9, **common_gbr_params)
        rul_q90.fit(X_rul_train, y_rul_train_clean)

        if len(X_rul_val) > 0:
            preds_median = rul_q50.predict(X_rul_val)
            mae = float(np.mean(np.abs(preds_median - y_rul_val_clean)))
            logger.info("RUL q50 val MAE: %.1f hours", mae)
    else:
        logger.warning(
            "Not enough RUL-labelled windows (%d) to train quantile regressors — "
            "RUL prediction will be unavailable in this bundle",
            len(X_rul_train),
        )

    # --- Feature importances and per-feature means ---
    importances = dict(zip(feature_cols, clf.feature_importances_.tolist()))
    feature_means = dict(zip(feature_cols, X_train.mean(axis=0).tolist()))

    bundle: dict[str, Any] = {
        "isolation_forest": iso,
        "classifier": clf,
        "rul_q10": rul_q10,
        "rul_q50": rul_q50,
        "rul_q90": rul_q90,
        "feature_names": feature_cols,
        "feature_importances": importances,
        "feature_means": feature_means,
        "failure_modes": [m for m in unique_labels if m != "HEALTHY"],
        "version": "v1.0.0",
        "trained_at": datetime.now(timezone.utc).isoformat(),
    }
    return bundle


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def get_available_model_codes() -> list[str]:
    """Return model codes for which training data exists."""
    if not TRAINING_DATA_DIR.exists():
        return []
    return [p.stem for p in TRAINING_DATA_DIR.glob("*.json")]


def train_one(model_code: str, passport: dict[str, Any]) -> None:
    """Load data, engineer features, train, and save bundle for one model_code."""
    records = load_training_data(model_code)
    windowed_df = build_windowed_features(records, passport)
    bundle = train_model_bundle(model_code, windowed_df)

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = MODELS_DIR / f"{model_code}.pkl"
    joblib.dump(bundle, out_path, compress=3)
    logger.info("Saved bundle to %s  (version=%s)", out_path, bundle["version"])


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train CASS ML model bundles from simulator-generated training data.",
    )
    parser.add_argument(
        "--model-code",
        type=str,
        default=None,
        help="Equipment model code to train (e.g. SRV-R740-2U). "
             "Omit to train all available models.",
    )
    parser.add_argument(
        "--passport",
        type=str,
        default=None,
        help=(
            "Path to a JSON file containing the equipment model passport. "
            "Required for proper contextual feature computation. "
            "If omitted, an empty passport is used (contextual features will be zero)."
        ),
    )
    args = parser.parse_args()

    if not TRAINING_DATA_DIR.exists():
        logger.error(
            "training_data/ directory not found at %s\n\n"
            "Generate training data first by running the simulator in offline mode:\n"
            "    cd simulator && node src/offline.js --output ../ml_service/training_data/",
            TRAINING_DATA_DIR,
        )
        sys.exit(1)

    # Load passport if provided; otherwise use empty (contextual features will be zeros)
    if args.passport:
        with open(args.passport, "r", encoding="utf-8") as fh:
            passport = json.load(fh)
        logger.info("Using passport from %s", args.passport)
    else:
        passport = {"channels": []}
        logger.warning(
            "No --passport provided — contextual features (dev_from_nominal, "
            "time_above_op, etc.) will all be zero. "
            "Pass --passport path/to/passport.json for best results."
        )

    model_codes: list[str]
    if args.model_code:
        model_codes = [args.model_code]
    else:
        model_codes = get_available_model_codes()
        if not model_codes:
            logger.error("No training data files found in %s", TRAINING_DATA_DIR)
            sys.exit(1)
        logger.info("Training all available models: %s", model_codes)

    for model_code in model_codes:
        logger.info("=" * 60)
        logger.info("Training model_code=%s", model_code)
        logger.info("=" * 60)
        try:
            train_one(model_code, passport)
        except Exception:
            logger.exception("Training failed for model_code=%s — skipping", model_code)

    logger.info("Done. Bundles saved to %s", MODELS_DIR)


if __name__ == "__main__":
    main()
